# Generated by Django 5.2.5 on 2025-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary of the article')),
                ('content', models.TextField(help_text='Main content of the article')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured article?')),
                ('is_published', models.BooleanField(default=False, help_text='Is this article published?')),
                ('published_date', models.DateTimeField(blank=True, help_text='Date when published', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Article Views',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
