# Generated by Django 5.2.5 on 2025-08-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Advertisement title for admin reference', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Advertisement image', null=True, upload_to='advertisements/')),
                ('link', models.URLField(blank=True, help_text='URL to redirect to when clicked')),
                ('content', models.TextField(blank=True, help_text='Text content for text-based ads')),
                ('is_active', models.BooleanField(default=True, help_text='Is this advertisement active?')),
                ('start_date', models.DateTimeField(help_text='When to start showing this advertisement')),
                ('end_date', models.DateTimeField(help_text='When to stop showing this advertisement')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority ads are shown first')),
            ],
            options={
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-priority', '-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Description of the vlog')),
                ('video_url', models.URLField(help_text='URL to the video (YouTube, Vimeo, etc.)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vlogs/thumbnails/')),
                ('is_featured', models.BooleanField(default=False, help_text='Is this a featured vlog?')),
                ('is_published', models.BooleanField(default=False, help_text='Is this vlog published?')),
                ('published_date', models.DateTimeField(blank=True, help_text='Date when published', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Vlogs',
                'ordering': ['-created_date'],
            },
        ),
    ]
