# Generated by Django 5.2.5 on 2025-08-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text="Subscriber's first name", max_length=50)),
                ('last_name', models.CharField(blank=True, help_text="Subscriber's last name", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this subscription active?')),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_weekly', models.BooleanField(default=True, help_text='Receive weekly newsletter')),
                ('receive_monthly', models.BooleanField(default=True, help_text='Receive monthly newsletter')),
                ('receive_events', models.BooleanField(default=True, help_text='Receive events content')),
                ('receive_food', models.BooleanField(default=True, help_text='Receive food content')),
                ('receive_spots', models.BooleanField(default=True, help_text='Receive new spots content')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='newsletter.newslettersubscriber')),
            ],
            options={
                'verbose_name_plural': 'Newsletter Preferences',
            },
        ),
    ]
