# Generated by Django 5.2.5 on 2025-08-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the comment author', max_length=100)),
                ('author_email', models.EmailField(help_text='Email of the comment author', max_length=254)),
                ('content', models.TextField(help_text='Comment content')),
                ('is_approved', models.BooleanField(default=False, help_text='Is this comment approved for public display?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of commenter', null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['created_date'],
            },
        ),
    ]
